version: '3'
services:
  deck:
    build:
        context: .
        dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - 8080:8080
    depends_on:
      - locks
      - decks
  locks:
    image: redis
  decks:
    image: redis
